version: 0.0
os: linux

files:
  - source: /
    destination: /home/ubuntu/app

hooks:
  BeforeInstall:
    - location: stop.sh
      timeout: 60
      runas: ec2-user

  AfterInstall:
    - location: set_permission.sh
      timeout: 30
      runas: ec2-user

  ApplicationStart:
    - location: start.sh
      timeout: 120
      runas: ec2-user

  ApplicationStop:
    - location: stop.sh
      timeout: 60
      runas: ec2-user
