version: 0.0
os: linux

files:
  - source: /
    destination: /home/ubuntu/backend

hooks:
  BeforeInstall:
    - location: stop.sh
      timeout: 60
      runas: ubuntu

  AfterInstall:
    - location: set_permission.sh
      timeout: 30
      runas: root

  ApplicationStart:
    - location: start.sh
      timeout: 120
      runas: ubuntu

  ApplicationStop:
    - location: stop.sh
      timeout: 60
      runas: ubuntu
