version: 0.2

phases:
  pre_build:
    commands:
      - echo "Starting pre-build phase"
      - chmod +x gradlew

  build:
    commands:
      - echo "Building Spring Boot application with Gradle"
      - ./gradlew clean build -x test

artifacts:
  files:
    - build/libs/*.jar
  discard-paths: yes
